#Запорожан Сергій ФІТ 3-8
ФІТ 3-8, КСВД ЛР-1


In [3]:

import numpy as np

1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [6]:
vector_natural = np.arange(1, 21)
print(vector_natural)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [7]:
unit_matrix_4x4 = np.ones((4, 4), dtype=float)
print(unit_matrix_4x4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [8]:
rand_matrix_uniform = np.random.uniform(-1, 1, size=(5, 5))
print(rand_matrix_uniform)

[[-0.09747042 -0.33826984  0.55964141 -0.28517345 -0.66506685]
 [ 0.90334614  0.12862642  0.5374531  -0.29554686  0.02591123]
 [-0.68523668  0.60139421  0.21545346  0.62089192 -0.84629856]
 [-0.07578205  0.94206012 -0.33242772  0.93436302 -0.80639532]
 [-0.88904042 -0.61744143 -0.5349412   0.63236337  0.63219787]]


4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [9]:
simple_rand_3x3 = np.random.random_sample((3, 3))
print(simple_rand_3x3)

[[0.95461159 0.54696329 0.20036466]
 [0.84091926 0.01106434 0.15418226]
 [0.59603317 0.98833863 0.33740459]]


5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [10]:
arr_x = np.random.randint(1, 21, size=6)
arr_y = np.random.randint(1, 21, size=6)
print(f"Масив X: {arr_x}")
print(f"Масив Y: {arr_y}")
print(f"Результат додавання: {np.add(arr_x, arr_y)}")
print(f"Результат віднімання: {np.subtract(arr_x, arr_y)}")
print(f"Результат множення: {np.multiply(arr_x, arr_y)}")

Масив X: [15 12 16 13 12  6]
Масив Y: [14 15 18  9  4 14]
Результат додавання: [29 27 34 22 16 20]
Результат віднімання: [ 1 -3 -2  4  8 -8]
Результат множення: [210 180 288 117  48  84]


6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [11]:
mat_alpha = np.random.randint(1, 6, size=(3, 2))
mat_beta = np.random.randint(1, 6, size=(2, 4))

result_product = mat_alpha @ mat_beta

print("Матриця 3x2:\n", mat_alpha)
print("Матриця 2x4:\n", mat_beta)
print("Результат множення матриць:\n", result_product)

Матриця 3x2:
 [[5 4]
 [3 4]
 [1 5]]
Матриця 2x4:
 [[3 1 5 2]
 [5 5 5 5]]
Результат множення матриць:
 [[35 25 45 30]
 [29 23 35 26]
 [28 26 30 27]]


7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [12]:
original_m = np.random.rand(3, 3)
transposed_m = np.transpose(original_m)

print("Оригінальна матриця:\n", original_m)
print("Транспонована матриця:\n", transposed_m)

Оригінальна матриця:
 [[0.48066555 0.36493458 0.61858152]
 [0.76089795 0.30960936 0.31099626]
 [0.7117318  0.26318116 0.98493954]]
Транспонована матриця:
 [[0.48066555 0.76089795 0.7117318 ]
 [0.36493458 0.30960936 0.26318116]
 [0.61858152 0.31099626 0.98493954]]


8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [13]:
mat_1 = np.random.randint(1, 11, (3, 3))
mat_2 = np.random.randint(1, 11, (3, 3))

difference = mat_1 - mat_2
print("Різниця матриць:\n", difference)

Різниця матриць:
 [[ 1  4 -7]
 [-2 -2  1]
 [ 0  0 -1]]


9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [14]:
m_left = np.random.randint(-5, 6, (3, 3))
m_right = np.random.randint(-5, 6, (3, 3))

final_dot = np.dot(m_left, m_right)
print("Результат добутку (dot):\n", final_dot)

Результат добутку (dot):
 [[-54 -14 -23]
 [-26 -14  12]
 [-37   8 -14]]


10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [15]:
main_matrix = np.random.uniform(-1, 1, (3, 3))
col_vector_sums = np.sum(main_matrix, axis=1).reshape(-1, 1)

print("Матриця:\n", main_matrix)
print("Вектор-стовпчик сум рядків:\n", col_vector_sums)

Матриця:
 [[-0.03500659 -0.18697609  0.87381899]
 [-0.99618901  0.33840712 -0.41782847]
 [ 0.36532968 -0.45634742 -0.93561228]]
Вектор-стовпчик сум рядків:
 [[ 0.65183631]
 [-1.07561036]
 [-1.02663002]]
